### PR TITLE
Fix debug assert with reordered ACKs

### PR DESCRIPTION
**Pull request by Ralith**
Fixes https://github.com/quinn-rs/quinn/issues/1889.

On careful examination, I think @tthebst's instinct was correct: the assert was fundamentally wrong, and our logic works as intended without it. I've hence removed the assert and attempted to better document why this is okay, but please double-check my thinking.

### CODE REVIEW

**Comment by rumenov** [comment]
Hello folks, when can we have this MR reviewed? 

The MR fixes our turmoil based unit tests of a library that uses QUINN. 
Fixing the unit tests will unblock the QUINN and RUSTLS upgrades on our side.

**Comment by djc** [comment]
Sorry, I want to spend a little time contemplating this change but haven't gotten to it. Hopefully in the next few days. Definitely haven't forgotten about it.

**Comment by rumenov** [comment]
> Sorry, I want to spend a little time contemplating this change but haven't gotten to it. Hopefully in the next few days. Definitely haven't forgotten about it.

Thank you @djc!

I was just worried it fell through the cracks because removing a debug_assert may seem unimportant.

**Review by djc — APPROVED** [review]
Sorry for the delay, this makes sense to me.

**Pull request merged**
