### PR TITLE
Port fix for address layout reliance to 0.8

### PR DESCRIPTION
**Pull request by djc**
I guess we should yank 0.1.{0,1,2}?

cc @est31 I'm not quite motivated to backport this to older versions than 0.8, but you might be interested.

### CODE REVIEW

**Review by Ralith — APPROVED** [review]

**Comment by Ralith** [comment]
> I guess we should yank 0.1.{0,1,2}?

Makes sense.

**Comment by djc** [comment]
Published 0.1.3 and yanked all previous versions.

**Comment by djc** [comment]
On second thought, I unyanked 0.1.2 so folks can take a little longer to upgrade, I guess? I'll yank it tomorrow.

**Comment by Ralith** [comment]
Doesn't yanking only affect new checkouts? It shouldn't be too disruptive unless people are pinning patch versions, which is unusual.

**Comment by est31** [comment]
Yanking affects people who have the version in their Cargo.lock too, because Cargo prints a warning in that instance. But admittedly this is only a light warning. I don't think that waiting is needed.

**Comment by djc** [comment]
Okay, yanked it again.

**Pull request merged**
