### PR TITLE
Upgrade rcgen to 0.9.1

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by djc** [comment]
(https://github.com/rust-fuzz/arbitrary/issues/99.)

**Comment by djc** [comment]
Yup, I'll fix that up tomorrow.

**Comment by Ralith** [comment]
> Only build fuzz targets against MSRV

Should this read "don't" instead of "only"?

**Comment by djc** [comment]
Err, yes!

**Comment by djc** [comment]
Fixed.

**Pull request merged**
