### PR TITLE
Allow initial maximum UDP payload size to be configured

### PR DESCRIPTION
**Pull request by Ralith**
Motivated by prospective user request. Also potentially useful for benchmark experimentation.

### CODE REVIEW

**Review by TimonPost — APPROVED** [review]
Looks good! And also a good comment to highlight potential issues.

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
Hmm, what is pulling in time?

**Comment by Ralith** [comment]
Looks like rcgen and tracing-subscriber. Is it time to bump MSRV anyway? Merging regardless since preexisting issue.

**Comment by djc** [comment]
Yeah, I think it's become too hard to avoid 1.56.

**Pull request merged**
