### PR TITLE
Unbreak Solaris build after #1993

### PR DESCRIPTION
**Pull request by psumbera**

### CODE REVIEW

**Review by mxinden — APPROVED** [review]
Sorry for the trouble @psumbera!

For others, concrete change introducing the regression:

https://github.com/quinn-rs/quinn/pull/1993/files#diff-b5b6c3bd850713c1d4e781f1b779473b699e1a4fa469defc6f07b3acd4348bd9L449

**Review by djc — APPROVED** [review]
Thanks! Needs a formatting fix, but the MSRV breakage is unrelated (caused by https://github.com/rust-fuzz/arbitrary/issues/202).

**Comment by djc** [comment]
(Also, would be nice to append a commit that bumps the version for quinn-udp so we can get a release out.)

**Comment by djc** [comment]
* Published quinn-udp v0.5.7 at registry `crates-io`
* [new tag]           quinn-udp-0.5.7 -> quinn-udp-0.5.7
* [Release notes](https://github.com/quinn-rs/quinn/releases/tag/quinn-udp-0.5.7)

**Pull request merged**
