### PR TITLE
bump versions to 0.9.4

### PR DESCRIPTION
**Pull request by lijunwangs**
bum quinn and quinn-proto version to 0.9.4

### CODE REVIEW

**Comment by lijunwangs** [comment]
Request to bump the version to 0.9.4 in 0.9.x release line. cc @djc @Ralith

**Comment by djc** [comment]
I suppose -proto should go to 0.9.3 instead?

**Review by Ralith — CHANGES_REQUESTED** [review]
Because the `quinn` changes rely on a new `quinn-proto` API, the dependency of `quinn` on `quinn-proto` must require the new version.

**Comment by lijunwangs** [comment]
> I suppose -proto should go to 0.9.3 instead?

I think somehow we have already have 0.9.3 for quinn-proto? https://docs.rs/quinn-proto/0.9.3/quinn_proto/index.html

**Comment by lijunwangs** [comment]
> Because the `quinn` changes rely on a new `quinn-proto` API, the dependency of `quinn` on `quinn-proto` must require the new version.

Updated dependency

**Review by lijunwangs — COMMENTED** [review]
These lint check errors are unrelated to this PR.

**Review by djc — APPROVED** [review]

**Comment by lijunwangs** [comment]
@djc @Ralith can you help merge this and release 0.9.4? Thanks!!

**Review by Ralith — APPROVED** [review]
LGTM, thanks!

**Comment by Ralith** [comment]
Published as 0.9.4.

**Pull request merged**
