### PR TITLE
Add visionOS support

### PR DESCRIPTION
**Pull request by rofferom**
Just enable the same code blocks than on iOS.

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
Hmm, I wonder if there is something better we can do, like treating all the Darwin stuff the same?

**Comment by rofferom** [comment]
Yes it would be great, especially because tvos support is missing too. I haven't tested it yet, that's why it isn't included in the MR.

**Comment by djc** [comment]
Do you know the right incantation for supporting everything Darwin at once?

**Comment by rofferom** [comment]
I have seen this one [`#[cfg(target_vendor = "apple")]`](https://github.com/rust-lang/rust/blob/1.81.0/library/std/src/sys/pal/unix/time.rs#L89). Other projects are using the same strategy than Quinn (ring, socket2).

Actually, I don't know the possible limitations of `#[cfg(target_vendor = "apple")]`.

**Comment by djc** [comment]
`#[cfg(target_vendor = "apple")]` looks about right to me. @Ralith what do you think?

**Comment by rofferom** [comment]
I have just added tvOS support with the current way to declare it. Waiting for Ralith's feedback to update the MR if required.

**Comment by djc** [comment]
Curious to hear what you're building!

**Review by Ralith — APPROVED** [review]

**Comment by Ralith** [comment]
> #[cfg(target_vendor = "apple")] looks about right to me (I noticed std/core use it in a few places). @Ralith what do you think?

That seems very appealing. I don't know how we'd verify that it's exactly the semantics we'd want short of digging into rustc, but it's hard to imagine it's too far off. Maybe switch to it in a separate commit so we can easily revert if needed?

**Pull request merged**
