### PR TITLE
chore(quinn-udp): tweak log levels

### PR DESCRIPTION
**Pull request by thomaseizinger**
This PR is a proposal to remove the two `ERROR` logs that we currently have in `quinn-udp`. Rationale is explained separately in each commit message.

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
This makes sense to me, thanks!

**Comment by thomaseizinger** [comment]
The CI failure seems like a fluke to me? Could you rerun those perhaps?

**Comment by djc** [comment]
This doesn't look like a fluke:

```rust
error: unused import: `error`
    --> quinn-udp\src\windows.rs:17:18
     |
  17 |     log::{debug, error},
     |                  ^^^^^
     |
     = note: `-D unused-imports` implied by `-D warnings`
     = help: to override `-D warnings` add `#[allow(unused_imports)]`
```

**Comment by thomaseizinger** [comment]
> This doesn't look like a fluke:
> 
> ```rust
> error: unused import: `error`
>     --> quinn-udp\src\windows.rs:17:18
>      |
>   17 |     log::{debug, error},
>      |                  ^^^^^
>      |
>      = note: `-D unused-imports` implied by `-D warnings`
>      = help: to override `-D warnings` add `#[allow(unused_imports)]`
> ```

Ah didn't see that in the output, makes sense!

**Review by Ralith — APPROVED** [review]
Thanks!

**Comment by thomaseizinger** [comment]
CI should be fixed now.

**Review by Ralith — APPROVED** [review]

**Pull request merged**
