### PR TITLE
feat(quinn, quinn-proto): add aws-lc-rs-fips feature flag

### PR DESCRIPTION
**Pull request by M0dEx**
Adds support for aws-lc-rs FIPS mode using a feature flag in quinn and quinn-proto.

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by M0dEx** [comment]
Seems the tests finished, but the `features` workflow has an issue due to a missing `golang` dependency of the FIPS mode.

**Comment by djc** [comment]
> The rustls project uses only the `ubuntu-latest` for feature combination checks, but I assume this project had a reason to have those run in a matrix over different OS's.

Yes, but it's fine to exempt the `fips` feature from the OS matrix and only support it on Linux given that's where it mainly makes sense per upstream guidance.

**Comment by M0dEx** [comment]
The `features` job should now skip FIPS on WIndows and macOS.

**Review by Ralith — APPROVED** [review]

**Review by djc — APPROVED** [review]
Thanks, looks great!

**Pull request merged**
