### PR TITLE
make example code truly async

### PR DESCRIPTION
**Pull request by dzvon**
In the original case, the code was actually running synchronously. So, fix it.

### CODE REVIEW

**Review by djc — APPROVED** [review]
LGTM, thanks!

**Review by djc — APPROVED** [review]

**Review by Ralith — CHANGES_REQUESTED** [review]
This looks like a no-op to me. `async { x.await }` is exactly the same as `x`, aside from inconsequential borrowck stuff. What makes you think it wasn't already async?

**Comment by dzvon** [comment]
I'm sorry, I misunderstood the meaning of the `futures::TryFutureExt::unwrap_or_else` method.

https://docs.rs/futures-util/0.3.17/futures_util/future/trait.TryFutureExt.html#method.unwrap_or_else
```
Unwraps this future's output, producing a future with this future's
[`Ok`](https://docs.rs/futures_core/*/futures_core/future/trait.TryFuture.html#associatedtype.Ok) type as its
[`Output`](https://docs.rs/core/*/core/future/future/trait.Future.html#associatedtype.Output) type.
```

```rust
tokio::spawn(x.unwrap_or_else(|_|{}));
```

In this example, I thought `x` will be `await`ed first, then the future producing by `unwrap_or_else` will be put in `spawn`. Thus the flow isn't async. Sorry, it's all right now. I'll close this PR.

Sorry for waste your time.

**Comment by Ralith** [comment]
No worries, we appreciate the thought!

**Pull request closed without merging**
