### PR TITLE
Expose the connections congestion window

### PR DESCRIPTION
**Pull request by Matthias247**
This can be useful for debugging performance issues

### CODE REVIEW

**Comment by Matthias247** [comment]
One alternative: This (as well as similar stats like `rtt`) details could also be returned via `ConnectionStats`. That allows the caller to get everything at once. That requires to add a new field (`path`? `recovery`? `reliability`?)

But maybe both options can be done.

**Review by Ralith — APPROVED** [review]
An aggregate return value is an interesting idea. I'd prefer not to have redundant interfaces, though. If we go that way, we should also remove the individual getters.

**Comment by djc** [comment]
Aggregating this stuff would be good. I wonder if it makes sense conceptually to fold everything into `ConnectionStats` or if we should maybe have two types: `ConnectionStats` for cumulative historic data, and `ConnectionState` for current data (names TBD, of course).

**Comment by Ralith** [comment]
That occurred to me as well, but I'm having trouble seeing concrete value in distinguishing them in the API.

**Comment by Matthias247** [comment]
same thought. But they are so often the same - e.g. total number of transmitted packets is historic data as well as current data, since it's a snapshot view

**Pull request closed without merging**
