### PR TITLE
bump versions to 0.10.2

### PR DESCRIPTION
**Pull request by lijunwangs**
bump versions to 0.10.2 in 0.10.x release line

### CODE REVIEW

**Comment by lijunwangs** [comment]
Request to bump versions to 0.10.2 in 0.10.x release line. cc @djc @Ralith

**Comment by lijunwangs** [comment]
> Can you cherry-pick the clippy lint fix from main?

Will look

**Comment by lijunwangs** [comment]
Thanks @djc -- I wonder when we can tag 0.10.2 and release it?

**Comment by djc** [comment]
I think we'll want to address #1608 before releasing 0.10.2.

**Pull request merged**
