### PR TITLE
Allow read_handshake to return keys.

### PR DESCRIPTION
**Pull request by dvc94ch**
This allows `quinn-noise` to work.

### CODE REVIEW

**Comment by Ralith** [comment]
Why does quinn-noise require this?

**Comment by dvc94ch** [comment]
Without this the connection times out:

```
Apr 19 09:25:15.538 TRACE recv{space=Handshake pn=0}: quinn_proto::connection: discarding Initial keys
Apr 19 09:25:15.538 TRACE recv{space=Handshake pn=0}: quinn_noise::session: write_handshake Handshake Server
Apr 19 09:25:15.541 TRACE recv{space=Handshake pn=0}: quinn_proto::connection: Data keys ready
Apr 19 09:25:15.541 TRACE recv{space=Handshake pn=0}: quinn_proto::connection: wrote 147 Handshake CRYPTO bytes
Apr 19 09:25:15.541 TRACE recv{space=Handshake pn=0}: quinn_noise::session: write_handshake Data Server
Apr 19 09:25:15.541 TRACE recv{space=Handshake pn=0}: quinn_proto::connection: discarding Handshake keys
Apr 19 09:25:15.541 TRACE recv{space=Handshake pn=0}: quinn_proto::connection: established
Apr 19 09:25:15.542 TRACE send{space=Data pn=0}: quinn_proto::connection: NEW_CONNECTION_ID sequence=1 id=1ba6cc83ababce4f
Apr 19 09:25:15.542 TRACE send{space=Data pn=0}: quinn_proto::connection: NEW_CONNECTION_ID sequence=2 id=7f98a2bfabfead2b
Apr 19 09:25:15.542 TRACE send{space=Data pn=0}: quinn_proto::connection: NEW_CONNECTION_ID sequence=3 id=96b7e96e4156d3ef
Apr 19 09:25:15.542 TRACE send{space=Data pn=0}: quinn_proto::connection: NEW_CONNECTION_ID sequence=4 id=8e9e0bc6d1d6455b
Apr 19 09:25:15.542 TRACE quinn_proto::connection: sending 139 bytes in 1 datagrams
Apr 19 09:25:15.544 DEBUG quinn_proto::connection: discarding unexpected Data packet (139 bytes)
Apr 19 09:25:15.594 TRACE quinn_proto::connection: timeout timer=LossDetection
Apr 19 09:25:15.594 TRACE quinn_proto::connection: PTO fired in_flight=43 count=1 space=Handshake
```

My interpretation of this log is that the packet contains a handshake and a data frame, and after reading the handshake frame the keys are available to read the data frame, but it takes until the next packet is sent for the write_handshake to return the data keys so that data frames can be read.

**Comment by dvc94ch** [comment]
I'll give it another try. I guess quinn-noise needs a wireshark plugin anyway. I can certainly add an additional round-trip to get it working (as the initial implementation using snow and a xx handshake also worked).

**Comment by Ralith** [comment]
In fact, "Data keys ready" suggests that `self.spaces[SpaceId::Data].crypto` is populated, whereas "discarding unexpected Data packet" suggests that it isn't, so there might be something funny going on.

**Comment by dvc94ch** [comment]
The "Data keys ready" is for the server right? It's the client rejecting the packet. This PR makes sure that the client also emits a "Data keys ready".

**Comment by Ralith** [comment]
That log message occurs on both sides. If the section you pasted has client/server arbitrarily interleaved then it's difficult to glean much from it.

**Comment by dvc94ch** [comment]
the handshake is half duplex so it's possible to figure out which side is logging which messages. all the ones up to and including `sending 139 bytes in 1 datagrams` are presumably generated by the server, while the last three are presumably generated by the client. but it does warrant further investigation.

**Comment by dvc94ch** [comment]
So the packets that are causing the connection to close are ping packets in the handshake space. Any ideas how to shed some more light on the issue?

**Comment by dvc94ch** [comment]
So the problem is:
client sends initial packet at which point the handshake keys are ready
client sends a ping packet using the handshake keys
server receives an initial packet at which point the handshake keys should be ready
server receives a ping packet and drops it
server writes a handshake packet at which point the handshake keys and data keys are ready
connection times out

**Comment by Ralith** [comment]
PING frames aren't normally part of the handshake, so if they're showing up something has probably already gone wrong (e.g. an expected flight not being received). From the logs you posted above, it looked like the dropped packet was using Data keys, not Handshake?

**Comment by dvc94ch** [comment]
The difference is I enabled 0rtt now which should use the handshake keys available after the initial message is sent in the quinn-noise case at least.

**Comment by Ralith** [comment]
0-RTT in QUIC uses data keys (which are derived from the cached keying material), not handshake keys.

Could you post separate trace logs for the client and server under your current configuration?

**Comment by Ralith** [comment]
To be clear, 0-RTT keys are not the same keys that get used for application data once the handshake completes, but are notionally in the applicatoin data space.

**Comment by dvc94ch** [comment]
I'll try again tomorrow, but couldn't get distinct logging for client/server to just work. This is the `merged` log in case you see something:

```
running 1 test
Apr 22 20:42:31.358  INFO smoke: 12D3KooWAGebPcyBra9YeZGtpsevudFM25j4BDT6rhwhPiMPE3rh
Apr 22 20:42:31.362  INFO smoke: 12D3KooWKzTHxXMDvjujbsN67RVm5DCA66i4B17SXHLdoevJcp2L
Apr 22 20:42:31.363 DEBUG libp2p_swarm: Listener ListenerId(1); New address: "/ip4/127.0.0.1/udp/53785/quic"    
Apr 22 20:42:31.366 DEBUG libp2p_quic::transport: dialing 127.0.0.1:53785
Apr 22 20:42:31.367 TRACE quinn_proto::endpoint: initial_dcid=b1709ce1f60d1bb7ef92d12d92a8330145c308c1
Apr 22 20:42:31.368 TRACE quinn_noise::session: write_handshake Initial Client
Apr 22 20:42:31.370 TRACE quinn_proto::connection: wrote 173 Initial CRYPTO bytes
Apr 22 20:42:31.370 TRACE quinn_noise::session: write_handshake ZeroRtt Client
Apr 22 20:42:31.370 TRACE quinn_proto::connection: Handshake keys ready
Apr 22 20:42:31.371 TRACE send{space=Initial pn=0}: quinn_proto::connection: CRYPTO: off 0 len 173
Apr 22 20:42:31.371 TRACE send{space=Initial pn=0}: quinn_proto::connection::packet_builder: PADDING * 968
Apr 22 20:42:31.371 TRACE quinn_proto::connection: sending 1200 bytes in 1 datagrams
Apr 22 20:42:31.373 TRACE first recv: quinn_proto::connection: authenticated
Apr 22 20:42:31.373 TRACE first recv:frame{ty=CRYPTO}: quinn_proto::connection: consumed 173 CRYPTO bytes
Apr 22 20:42:31.373 TRACE first recv:frame{ty=CRYPTO}: quinn_noise::session: read_handshake Initial Server
Apr 22 20:42:31.375 TRACE first recv: quinn_noise::session: write_handshake ZeroRtt Server
Apr 22 20:42:31.375 TRACE first recv: quinn_proto::connection: Handshake keys ready
Apr 22 20:42:31.375 TRACE quinn_proto::endpoint: connection incoming id=0 icid=b1709ce1f60d1bb7ef92d12d92a8330145c308c1
Apr 22 20:42:31.376 DEBUG libp2p_swarm: Connection established: Connected { endpoint: Dialer { address: "/ip4/127.0.0.1/udp/53785/quic/p2p/12D3KooWAGebPcyBra9YeZGtpsevudFM25j4BDT6rhwhPiMPE3rh" }, peer_id: PeerId("12D3KooWAGebPcyBra9YeZGtpsevudFM25j4BDT6rhwhPiMPE3rh") }; Total (peer): 1.    
Apr 22 20:42:31.376 TRACE send{space=Initial pn=0}: quinn_proto::connection: ACK
Apr 22 20:42:31.376 DEBUG libp2p_swarm: Connection established: Connected { endpoint: Listener { local_addr: "/ip4/127.0.0.1/udp/53785/quic", send_back_addr: "/ip4/127.0.0.1/udp/45003/quic" }, peer_id: PeerId("12D3KooWKzTHxXMDvjujbsN67RVm5DCA66i4B17SXHLdoevJcp2L") }; Total (peer): 1.    
Apr 22 20:42:31.376 TRACE quinn_proto::connection: sending 51 bytes in 1 datagrams
Apr 22 20:42:31.377 TRACE quinn_proto::connection: got Initial packet (51 bytes) from 127.0.0.1:53785 using id b546386c9f4c26d4
Apr 22 20:42:31.377 TRACE recv{space=Initial pn=0}: quinn_proto::connection: authenticated
Apr 22 20:42:31.377 TRACE recv{space=Initial pn=0}: quinn_proto::connection: switching remote CID to 65af031ded479c15
Apr 22 20:42:31.377 TRACE recv{space=Initial pn=0}: quinn_noise::session: write_handshake Handshake Client
Apr 22 20:42:32.370 TRACE quinn_proto::connection: timeout timer=LossDetection
Apr 22 20:42:32.371 TRACE quinn_proto::connection: PTO fired in_flight=0 count=0 space=Handshake
Apr 22 20:42:32.408 TRACE quinn_proto::connection: discarding Initial keys
Apr 22 20:42:32.409 TRACE send{space=Handshake pn=0}: quinn_proto::connection: PING
Apr 22 20:42:32.409 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:32.410 TRACE send{space=Handshake pn=1}: quinn_proto::connection: PING
Apr 22 20:42:32.410 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:32.411 TRACE quinn_proto::connection: got Handshake packet (43 bytes) from 127.0.0.1:45003 using id 65af031ded479c15
Apr 22 20:42:32.412 TRACE recv{space=Handshake pn=0}: quinn_proto::connection: authenticated
Apr 22 20:42:32.412 TRACE recv{space=Handshake pn=0}: quinn_proto::connection: discarding Initial keys
Apr 22 20:42:32.412 TRACE recv{space=Handshake pn=0}: quinn_noise::session: write_handshake Handshake Server
Apr 22 20:42:32.416 TRACE recv{space=Handshake pn=0}: quinn_proto::connection: Data keys ready
Apr 22 20:42:32.416 TRACE recv{space=Handshake pn=0}: quinn_proto::connection: wrote 147 Handshake CRYPTO bytes
Apr 22 20:42:32.416 TRACE recv{space=Handshake pn=0}: quinn_noise::session: write_handshake Data Server
Apr 22 20:42:32.416 TRACE recv{space=Handshake pn=0}: quinn_proto::connection: discarding Handshake keys
Apr 22 20:42:32.417 TRACE recv{space=Handshake pn=0}: quinn_proto::connection: established
Apr 22 20:42:32.417 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:32.417 TRACE send{space=Data pn=0}: quinn_proto::connection: NEW_CONNECTION_ID sequence=1 id=3997f94eefc749b1
Apr 22 20:42:32.417 TRACE send{space=Data pn=0}: quinn_proto::connection: NEW_CONNECTION_ID sequence=2 id=28bd766e069a0fb4
Apr 22 20:42:32.417 TRACE send{space=Data pn=0}: quinn_proto::connection: NEW_CONNECTION_ID sequence=3 id=88aa2cae340b00ea
Apr 22 20:42:32.418 TRACE send{space=Data pn=0}: quinn_proto::connection: NEW_CONNECTION_ID sequence=4 id=e331b4b965007d28
Apr 22 20:42:32.418 TRACE quinn_proto::connection: sending 139 bytes in 1 datagrams
Apr 22 20:42:32.419 DEBUG quinn_proto::connection: discarding unexpected Data packet (139 bytes)
Apr 22 20:42:32.447 TRACE quinn_proto::connection: timeout timer=LossDetection
Apr 22 20:42:32.447 TRACE quinn_proto::connection: PTO fired in_flight=86 count=1 space=Handshake
Apr 22 20:42:32.486 TRACE send{space=Handshake pn=2}: quinn_proto::connection: PING
Apr 22 20:42:32.486 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:32.486 TRACE send{space=Handshake pn=3}: quinn_proto::connection: PING
Apr 22 20:42:32.487 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:32.487 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:32.488 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:32.562 TRACE quinn_proto::connection: timeout timer=LossDetection
Apr 22 20:42:32.562 TRACE quinn_proto::connection: PTO fired in_flight=172 count=2 space=Handshake
Apr 22 20:42:32.639 TRACE send{space=Handshake pn=4}: quinn_proto::connection: PING
Apr 22 20:42:32.640 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:32.640 TRACE send{space=Handshake pn=5}: quinn_proto::connection: PING
Apr 22 20:42:32.640 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:32.641 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:32.641 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:32.792 TRACE quinn_proto::connection: timeout timer=LossDetection
Apr 22 20:42:32.792 TRACE quinn_proto::connection: PTO fired in_flight=258 count=3 space=Handshake
Apr 22 20:42:32.945 TRACE send{space=Handshake pn=6}: quinn_proto::connection: PING
Apr 22 20:42:32.946 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:32.946 TRACE send{space=Handshake pn=7}: quinn_proto::connection: PING
Apr 22 20:42:32.947 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:32.947 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:32.947 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:33.251 TRACE quinn_proto::connection: timeout timer=LossDetection
Apr 22 20:42:33.251 TRACE quinn_proto::connection: PTO fired in_flight=344 count=4 space=Handshake
Apr 22 20:42:33.558 TRACE send{space=Handshake pn=8}: quinn_proto::connection: PING
Apr 22 20:42:33.558 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:33.559 TRACE send{space=Handshake pn=9}: quinn_proto::connection: PING
Apr 22 20:42:33.559 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:33.560 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:33.560 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:34.169 TRACE quinn_proto::connection: timeout timer=LossDetection
Apr 22 20:42:34.170 TRACE quinn_proto::connection: PTO fired in_flight=430 count=5 space=Handshake
Apr 22 20:42:34.781 TRACE send{space=Handshake pn=10}: quinn_proto::connection: PING
Apr 22 20:42:34.782 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:34.782 TRACE send{space=Handshake pn=11}: quinn_proto::connection: PING
Apr 22 20:42:34.783 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:34.783 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:34.784 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:36.005 TRACE quinn_proto::connection: timeout timer=LossDetection
Apr 22 20:42:36.005 TRACE quinn_proto::connection: PTO fired in_flight=516 count=6 space=Handshake
Apr 22 20:42:37.229 TRACE send{space=Handshake pn=12}: quinn_proto::connection: PING
Apr 22 20:42:37.229 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:37.230 TRACE send{space=Handshake pn=13}: quinn_proto::connection: PING
Apr 22 20:42:37.230 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:37.231 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:37.231 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:39.676 TRACE quinn_proto::connection: timeout timer=LossDetection
Apr 22 20:42:39.676 TRACE quinn_proto::connection: PTO fired in_flight=602 count=7 space=Handshake
Apr 22 20:42:41.373 TRACE quinn_proto::connection: timeout timer=LossDetection
Apr 22 20:42:41.373 TRACE quinn_proto::connection: PTO fired in_flight=139 count=0 space=Data
Apr 22 20:42:41.373 TRACE quinn_proto::connection: timeout timer=LossDetection
Apr 22 20:42:41.373 TRACE quinn_proto::connection: PTO fired in_flight=139 count=1 space=Data
Apr 22 20:42:41.374 TRACE quinn_proto::connection: timeout timer=LossDetection
Apr 22 20:42:41.374 TRACE quinn_proto::connection: PTO fired in_flight=139 count=2 space=Data
Apr 22 20:42:41.374 TRACE quinn_proto::connection: timeout timer=LossDetection
Apr 22 20:42:41.374 TRACE quinn_proto::connection: PTO fired in_flight=139 count=3 space=Data
Apr 22 20:42:42.123 TRACE send{space=Handshake pn=14}: quinn_proto::connection: PING
Apr 22 20:42:42.123 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:42.124 TRACE send{space=Handshake pn=15}: quinn_proto::connection: PING
Apr 22 20:42:42.124 TRACE quinn_proto::connection: sending 43 bytes in 1 datagrams
Apr 22 20:42:42.125 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:42.125 TRACE send{space=Data pn=1}: quinn_proto::connection: NEW_CONNECTION_ID sequence=4 id=e331b4b965007d28
Apr 22 20:42:42.126 TRACE send{space=Data pn=1}: quinn_proto::connection: NEW_CONNECTION_ID sequence=3 id=88aa2cae340b00ea
Apr 22 20:42:42.126 TRACE send{space=Data pn=1}: quinn_proto::connection: NEW_CONNECTION_ID sequence=2 id=28bd766e069a0fb4
Apr 22 20:42:42.126 TRACE send{space=Data pn=1}: quinn_proto::connection: NEW_CONNECTION_ID sequence=1 id=3997f94eefc749b1
Apr 22 20:42:42.126 TRACE quinn_proto::connection: sending 139 bytes in 1 datagrams
Apr 22 20:42:42.127 TRACE send{space=Data pn=2}: quinn_proto::connection: NEW_CONNECTION_ID sequence=1 id=3997f94eefc749b1
Apr 22 20:42:42.127 TRACE send{space=Data pn=2}: quinn_proto::connection: NEW_CONNECTION_ID sequence=2 id=28bd766e069a0fb4
Apr 22 20:42:42.127 TRACE send{space=Data pn=2}: quinn_proto::connection: NEW_CONNECTION_ID sequence=3 id=88aa2cae340b00ea
Apr 22 20:42:42.127 TRACE send{space=Data pn=2}: quinn_proto::connection: NEW_CONNECTION_ID sequence=4 id=e331b4b965007d28
Apr 22 20:42:42.128 TRACE quinn_proto::connection: sending 139 bytes in 1 datagrams
Apr 22 20:42:42.128 DEBUG quinn_proto::connection: discarding unexpected Data packet (139 bytes)
Apr 22 20:42:42.128 TRACE send{space=Data pn=3}: quinn_proto::connection: NEW_CONNECTION_ID sequence=4 id=e331b4b965007d28
Apr 22 20:42:42.128 TRACE send{space=Data pn=3}: quinn_proto::connection: NEW_CONNECTION_ID sequence=3 id=88aa2cae340b00ea
Apr 22 20:42:42.128 TRACE send{space=Data pn=3}: quinn_proto::connection: NEW_CONNECTION_ID sequence=2 id=28bd766e069a0fb4
Apr 22 20:42:42.128 TRACE send{space=Data pn=3}: quinn_proto::connection: NEW_CONNECTION_ID sequence=1 id=3997f94eefc749b1
Apr 22 20:42:42.129 TRACE quinn_proto::connection: sending 139 bytes in 1 datagrams
Apr 22 20:42:42.129 DEBUG quinn_proto::connection: discarding unexpected Data packet (139 bytes)
Apr 22 20:42:42.129 TRACE send{space=Data pn=4}: quinn_proto::connection: NEW_CONNECTION_ID sequence=1 id=3997f94eefc749b1
Apr 22 20:42:42.129 TRACE send{space=Data pn=4}: quinn_proto::connection: NEW_CONNECTION_ID sequence=2 id=28bd766e069a0fb4
Apr 22 20:42:42.129 TRACE send{space=Data pn=4}: quinn_proto::connection: NEW_CONNECTION_ID sequence=3 id=88aa2cae340b00ea
Apr 22 20:42:42.129 TRACE send{space=Data pn=4}: quinn_proto::connection: NEW_CONNECTION_ID sequence=4 id=e331b4b965007d28
Apr 22 20:42:42.129 DEBUG quinn_proto::connection: discarding unexpected Data packet (139 bytes)
Apr 22 20:42:42.130 TRACE quinn_proto::connection: sending 139 bytes in 1 datagrams
Apr 22 20:42:42.130 TRACE send{space=Data pn=5}: quinn_proto::connection: NEW_CONNECTION_ID sequence=4 id=e331b4b965007d28
Apr 22 20:42:42.130 TRACE send{space=Data pn=5}: quinn_proto::connection: NEW_CONNECTION_ID sequence=3 id=88aa2cae340b00ea
Apr 22 20:42:42.130 TRACE send{space=Data pn=5}: quinn_proto::connection: NEW_CONNECTION_ID sequence=2 id=28bd766e069a0fb4
Apr 22 20:42:42.130 TRACE send{space=Data pn=5}: quinn_proto::connection: NEW_CONNECTION_ID sequence=1 id=3997f94eefc749b1
Apr 22 20:42:42.131 TRACE quinn_proto::connection: sending 139 bytes in 1 datagrams
Apr 22 20:42:42.131 DEBUG quinn_proto::connection: discarding unexpected Data packet (139 bytes)
Apr 22 20:42:42.131 TRACE send{space=Data pn=6}: quinn_proto::connection: NEW_CONNECTION_ID sequence=1 id=3997f94eefc749b1
Apr 22 20:42:42.131 TRACE send{space=Data pn=6}: quinn_proto::connection: NEW_CONNECTION_ID sequence=2 id=28bd766e069a0fb4
Apr 22 20:42:42.131 TRACE send{space=Data pn=6}: quinn_proto::connection: NEW_CONNECTION_ID sequence=3 id=88aa2cae340b00ea
Apr 22 20:42:42.131 TRACE send{space=Data pn=6}: quinn_proto::connection: NEW_CONNECTION_ID sequence=4 id=e331b4b965007d28
Apr 22 20:42:42.132 TRACE quinn_proto::connection: sending 139 bytes in 1 datagrams
Apr 22 20:42:42.132 DEBUG quinn_proto::connection: discarding unexpected Data packet (139 bytes)
Apr 22 20:42:42.132 TRACE send{space=Data pn=7}: quinn_proto::connection: NEW_CONNECTION_ID sequence=4 id=e331b4b965007d28
Apr 22 20:42:42.132 TRACE send{space=Data pn=7}: quinn_proto::connection: NEW_CONNECTION_ID sequence=3 id=88aa2cae340b00ea
Apr 22 20:42:42.132 TRACE send{space=Data pn=7}: quinn_proto::connection: NEW_CONNECTION_ID sequence=2 id=28bd766e069a0fb4
Apr 22 20:42:42.132 TRACE send{space=Data pn=7}: quinn_proto::connection: NEW_CONNECTION_ID sequence=1 id=3997f94eefc749b1
Apr 22 20:42:42.133 TRACE quinn_proto::connection: sending 139 bytes in 1 datagrams
Apr 22 20:42:42.133 DEBUG quinn_proto::connection: discarding unexpected Data packet (139 bytes)
Apr 22 20:42:42.133 TRACE send{space=Data pn=8}: quinn_proto::connection: NEW_CONNECTION_ID sequence=1 id=3997f94eefc749b1
Apr 22 20:42:42.133 TRACE send{space=Data pn=8}: quinn_proto::connection: NEW_CONNECTION_ID sequence=2 id=28bd766e069a0fb4
Apr 22 20:42:42.133 TRACE send{space=Data pn=8}: quinn_proto::connection: NEW_CONNECTION_ID sequence=3 id=88aa2cae340b00ea
Apr 22 20:42:42.133 TRACE send{space=Data pn=8}: quinn_proto::connection: NEW_CONNECTION_ID sequence=4 id=e331b4b965007d28
Apr 22 20:42:42.134 TRACE quinn_proto::connection: sending 139 bytes in 1 datagrams
Apr 22 20:42:42.134 DEBUG quinn_proto::connection: discarding unexpected Data packet (139 bytes)
Apr 22 20:42:42.134 DEBUG quinn_proto::connection: discarding unexpected Handshake packet (43 bytes)
Apr 22 20:42:42.134 DEBUG quinn_proto::connection: discarding unexpected Data packet (139 bytes)
Apr 22 20:42:42.409 TRACE quinn_proto::connection: timeout timer=Idle
Apr 22 20:42:42.409 TRACE quinn_proto::connection: connection closed
Apr 22 20:42:42.409 DEBUG libp2p_quic::muxer: connection lost because of timed out
Apr 22 20:42:42.412 TRACE quinn_proto::connection: timeout timer=Idle
Apr 22 20:42:42.412 TRACE quinn_proto::connection: connection closed
Apr 22 20:42:42.412 DEBUG libp2p_quic::muxer: connection lost because of timed out
Apr 22 20:42:42.412 DEBUG libp2p_swarm: Connection Connected { endpoint: Listener { local_addr: "/ip4/127.0.0.1/udp/53785/quic", send_back_addr: "/ip4/127.0.0.1/udp/45003/quic" }, peer_id: PeerId("12D3KooWKzTHxXMDvjujbsN67RVm5DCA66i4B17SXHLdoevJcp2L") } closed: IO(Custom { kind: Other, error: ConnectionLost { reason: TimedOut } })    
Apr 22 20:42:42.413 ERROR panic: thread 'smoke' panicked at 'ConnectionClosed { peer_id: PeerId("12D3KooWKzTHxXMDvjujbsN67RVm5DCA66i4B17SXHLdoevJcp2L"), endpoint: Listener { local_addr: "/ip4/127.0.0.1/udp/53785/quic", send_back_addr: "/ip4/127.0.0.1/udp/45003/quic" }, num_established: 0, cause: Some(IO(Custom { kind: Other, error: ConnectionLost { reason: TimedOut } })) }': tests/smoke.rs:95    
test smoke ... FAILED
```

**Comment by Ralith** [comment]
> ```
> Apr 22 20:42:31.370 TRACE quinn_noise::session: write_handshake ZeroRtt Client
> Apr 22 20:42:31.370 TRACE quinn_proto::connection: Handshake keys ready
> ```

Are you returning 0-RTT keys where where handshake keys are expected? 0-RTT keys should only be yielded through the `Session::early_crypto` method.

The other thing that jumps out at me is that the server never sends any data in the handshake space, which is what the client's waiting for. I'm guessing your `write_handshake Handshake Client` log indicates that the client's `write_handshake` method is being called and returning nothing, after which no progress can be made, because the server seemingly has no further crypto data to send.

**Comment by dvc94ch** [comment]
> Are you returning 0-RTT keys where where handshake keys are expected? 0-RTT keys should only be yielded through the Session::early_crypto method.

A 0-RTT key is the same as a handshake key in quinn-noise. After the initial message was sent we cache the handshake key as a 0rtt key.

**Comment by Ralith** [comment]
Your log messages include both "write_handshake ZeroRtt Client" and "write_handshake Handshake Client". `write_handshake` should never return 0-RTT keys. and there's only one set of handshake keys.

**Comment by dvc94ch** [comment]
So with this PR we have three states:
```
write_handshake
State::Initial Side::Client
State::Handshake Side::Server
read_handshake
State::Initial Side::Server
State::Handshake Side::Client
```
without this PR we have:
```
write_handshake:
State::Initial Side::Client
State::ZeroRtt  _
State::Handshake Side::Server
State::OneRtt _
read_handshake:
State::Initial Side::Server
State::Handshake Side::Client
```
I can add the transitions but I think they're clear. `Initial->ZeroRtt->Handshake->OneRtt` for both client/server.

**Comment by Ralith** [comment]
The logs you pasted include:
> `Apr 22 20:42:31.377 TRACE recv{space=Initial pn=0}: quinn_noise::session: write_handshake Handshake Client`

That doesn't seem to be consistent with the above.

**Comment by dvc94ch** [comment]
`write_handshake Handshake Client` is a wait state and will return `None` (you can see that in the log by not having a `wrote n crypto bytes` after it was called). the only way for the handshake to make progress is for `read_handshake Handshake Client` to be emitted which will advance the state to OneRtt after which a write_handshake will result in `Datakeys ready`.

I'm not sure what's so fundamentally wrong with this PR. I can make the handshake look like a tls handshake to quinn by adding more pseudo states that don't do anything (which while messy did work previously) and is probably a bit harder now it's a two way handshake instead of a threeway. I don't see why allowing for handshakes that don't have the exact same sequence of states as tls is bad.

**Comment by dvc94ch** [comment]
oh there is a different patch that also fixes the problem:
```
diff --git a/quinn-proto/src/connection/mod.rs b/quinn-proto/src/connection/mod.rs
index d7fe2d1e..b0ad861d 100644
--- a/quinn-proto/src/connection/mod.rs
+++ b/quinn-proto/src/connection/mod.rs
@@ -1542,7 +1542,9 @@ where
         loop {
             let space = self.highest_space;
             let mut outgoing = Vec::new();
+            let mut new_keys = false;
             if let Some(crypto) = self.crypto.write_handshake(&mut outgoing) {
+                new_keys = true;
                 match space {
                     SpaceId::Initial => {
                         self.upgrade_crypto(SpaceId::Handshake, crypto);
@@ -1553,7 +1555,7 @@ where
                     _ => unreachable!("got updated secrets during 1-RTT"),
                 }
             }
-            if outgoing.is_empty() {
+            if outgoing.is_empty() && !new_keys {
                 break;
             }
             let offset = self.spaces[space].crypto_offset;
```

**Comment by Ralith** [comment]
> I don't see why allowing for handshakes that don't have the exact same sequence of states as tls is bad.

It's not clear to me that the current interface has that requirement.

> oh there is a different patch that also fixes the problem

That looks much more reasonable to me, as it doesn't complicate any interface--in fact it's arguably a simplification. I'm guessing this means that the root problem in the above trace is that you want the server to advance directly to the Data space after receiving the client's first flight?

> However this results in the Handshake being added to the Initial packet space instead of the Handshake packet space

Sorry, I don't follow this. What do you mean by "the Handshake?" Data encrypted with handshake keys is, by definition, in the initial packet space; it is impossible to use multiple keys within the same QUIC packet, though multiple QUIC packets may be coalesced into a single UDP packet. Data yielded by `write_handshake` will be encrypted with the keys most recently returned.

**Comment by dvc94ch** [comment]
> Sorry, I don't follow this. What do you mean by "the Handshake?" Data encrypted with handshake keys is, by definition, not in the initial packet space; it is impossible to use multiple keys within the same QUIC packet, though multiple QUIC packets may be coalesced into a single UDP datagram. Data yielded by write_handshake will be encrypted with the keys most recently returned.

The first message from the server needs to be encrypted with the handshake keys. To accomplish that the handshake keys need to be returned before the crypto frame encrypted with the handshake keys. This can be accomplished by letting read_handshake return keys or letting write_handshake return keys before returning the crypto frame. Essentially in the servers turn it performs the following steps:

1. compute the handshake keys from the initial message from the client
2. sends a handshake message so the client can compute the data keys
3. compute the data keys

so the problem is that if you do 2 before 1 the wrong message space is used.

Anyway if the above patch is ok I can open a PR, I'm happy with that solution.

**Comment by Ralith** [comment]
> This can be accomplished by letting read_handshake return keys or letting write_handshake return keys before returning the crypto frame

Oh, you meant that issues would arise *without* the change. Yeah, I can see that.

> Anyway if the above patch is ok I can open a PR, I'm happy with that solution.

That would be great, thanks! I think it's an elegant solution. As a minor style nit, you could replace `new_keys` with `space != self.highest_space`, since the latter is updated on `upgrade_keys`.

**Pull request closed without merging**
